<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 9</p>

In [32]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets, model_selection

In [33]:
# Import the built-in iris dataset to work with
iris = datasets.load_iris() # the dataset consists of 3 different types of irises' (Setosa, Versicolour, and Virginica) petal and sepal length
print("iris dataset",iris.data[:10,:])
X = iris.data[:, :2] # We only want to use the first two features (Sepal Length, Sepal Width)
y = iris.target # corresponding to 'setosa', 'versicolor', 'virginica
print("iris target",y[:10,])

iris dataset [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
iris target [0 0 0 0 0 0 0 0 0 0]


In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [35]:
# Develop a linear Support Vector Machine to classify the irises
# Use GridSearchCV to optimize the model's hyperparameters (C, gamma, kernel)
# Compare the accuracies of the above two models


### Develop a linear Support Vector Machine to classify the irises

In [36]:
model = svm.SVC(C= 1, gamma= 0.01, kernel= 'rbf', random_state=42) # C: regularization parameter
                                                               # Gamma: kernel coeff.,the ‘spread’ of the kernel/decision region. When gamma is low, the ‘curve’ of the decision boundary is very low and thus the decision region is very broad.
model.fit(X_train,y_train)
predictions = model.predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,predictions))

[[13  0  0]
 [11  0  9]
 [ 0  0 12]]


### Use GridSearchCV to optimize the model's hyperparameters (C, gamma, kernel)


In [38]:
from sklearn.model_selection import GridSearchCV  # looks for optimization of hyperparameters over predefined values by fitting the estimator (model) on the training set
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 
grid = GridSearchCV(svm.SVC(),param_grid,refit=True,verbose=3)  # refits the estimator using the best found parameters
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.619 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.619 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.714 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.333 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [39]:
grid.best_params_  # Parameter setting that gave the best results

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}

In [40]:
grid.best_estimator_  # estimator which gave highest score

SVC(C=100, gamma=0.01)

In [41]:
grid_predictions = grid.predict(X_test)

In [42]:
print(confusion_matrix(y_test,grid_predictions))

[[12  1  0]
 [ 0 15  5]
 [ 0  5  7]]


### Compare the accuracies of the above two models

The confusion matrix with GridSearchCV is clearly more accurate than the simple SVC model. The first model can only predict 2 classifications, failing to identify the versicolor variety. The GridSearchCV model is able to classify all 3 varieties 